# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

FastBellmanTangent <- function(strike, discount, n_dec, grid, disturb, weight) {
    .Call('_ConvexPaper_FastBellmanTangent', PACKAGE = 'ConvexPaper', strike, discount, n_dec, grid, disturb, weight)
}

FastBellmanUpper <- function(strike, discount, n_dec, grid, lipz, disturb, weight) {
    .Call('_ConvexPaper_FastBellmanUpper', PACKAGE = 'ConvexPaper', strike, discount, n_dec, grid, lipz, disturb, weight)
}

