# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BermudaPutUpper <- function(strike, discount, n_dec, grid, lipz, disturb, weight) {
    .Call('_ConvexPaper_BermudaPutUpper', PACKAGE = 'ConvexPaper', strike, discount, n_dec, grid, lipz, disturb, weight)
}

FastBermudaPutTangent <- function(strike, discount, n_dec, grid, disturb, weight) {
    .Call('_ConvexPaper_FastBermudaPutTangent', PACKAGE = 'ConvexPaper', strike, discount, n_dec, grid, disturb, weight)
}

FastInfBermudaPutTangent <- function(strike, discount, grid, disturb, weight, max_iter, error) {
    .Call('_ConvexPaper_FastInfBermudaPutTangent', PACKAGE = 'ConvexPaper', strike, discount, grid, disturb, weight, max_iter, error)
}

InfBermudaPutUpper <- function(strike, discount, grid, lipz, disturb, weight, max_iter, error) {
    .Call('_ConvexPaper_InfBermudaPutUpper', PACKAGE = 'ConvexPaper', strike, discount, grid, lipz, disturb, weight, max_iter, error)
}

